[package]
name = "ip-pinger"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
clap = { version = "4.5.4", features = ["derive"] }
dns-lookup = "2.0.4"
fastping-rs = "0.2.4"
rand = "0.8.5"
